#+title: Внятное ТЗ
#+author: Kopnov Alexandr
#+date: 2023-04-18
#+LANGUAGE: ru
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper,fleqn,12pt]
#+LATEX_HEADER: \usepackage[lmargin=15mm, rmargin=15mm, tmargin=2cm, bmargin=2cm]{geometry}
* Функциональные требования

** Регистрация/авторизация

Через почту
** Различные типы ролей

+ Админ
+ Пользователь

** Главная доска

Нужны пояснения
** Задачи

Задача содержит:
+ название
+ описание
+ дата (постановка,дедлайн?)
+ тип задачи (по канбану?)
+ кому назначена
+ кем назначена
*** Назначение задач

Тип задачи ставится администратором, и только администратор может его
редактировать.

** Аналитика (статистика)

+ На главной странице краткий анализ
+ У каждого пользователя должна быть статистика по выполнению задач

** База данных персонала

Необходимые на предприятии данные о персонале
** Создание проектных досок

Администраторы могут создавать доски проекта, доступные приглашённым туда
пользователям.
** Фильтрация задач
Можно искать задачи с использованием в качестве фильтра типа, пользователя и дату

** Возможность просмотра заданий админом

Чтобы остальной персонал не смог просматривать описание задачи на доске.

Насколько понимаю, речь о том, что описание задачи может просматривать
администратор и те, кому она назначена.

* Реализация

Для системы используем =drf=. В качестве базы данных
предлагается =postgresql=, так как есть опыт работы с ним. Также предлагаю
использовать контейнеры =docker=, с ними также работали до этого.

** Авторизация

Через django

** Типы пользователей

Предлагаю использовать систему тэгов: каждому пользователю соответствует список
групп, которым он принадлежит. Это может соответствовать подразделению,
должности, статусу администратора, участию в проекте.

Ниже написаны связи такой системы с другими пунктами ТЗ

*** БД персонала

Предполагается форма взаимного соответствия тэгов и "необходимых на предприятии данных
о персонале". Возможно, в тэгах будет дополнительная информация
*** Задачи

Возможность назначать задачи всем пользователям в проекте с определённым тэгом,
либо искать по тэгам человека, которому будет назначена задача.

*** Проектные доски

При приглашении пользователей фильтрация по тэгам.

** Задачи и аналитика

Аналитика подразумевает, что у задачи есть подпункты, т.е. задача может быть
выполнена не полностью. Чтобы не разбираться с генерацией подзадач, если они не
выделены, предлагаю хранить статус задачи отдельно, таким образом можно пометить
задачу как выполненную, не выполнив все подпункты.

Отображать нужно процент выполнения и факт нарушения дедлайнов.

Возможность запросить review у админа.
