# Generated by Django 4.2.1 on 2023-05-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(to='yatapp.group'),
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
