# Generated by Django 4.2 on 2023-04-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subtasks',
            new_name='Subtask',
        ),
    ]
