# Generated by Django 4.2 on 2023-05-09 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatapp', '0002_alter_profile_groups_delete_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='header',
            field=models.TextField(default='test', validators=[django.core.validators.MaxLengthValidator(99)]),
            preserve_default=False,
        ),
    ]
