# Generated by Django 4.2 on 2023-05-10 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatapp', '0003_task_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.TextField(default='', validators=[django.core.validators.MaxLengthValidator(999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
