# Generated by Django 4.2 on 2023-05-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yatapp', '0004_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_permissions',
        ),
    ]
