# Generated by Django 4.2 on 2023-05-10 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatapp', '0004_board_description_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(default='', validators=[django.core.validators.MaxLengthValidator(999)]),
        ),
    ]
